apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-nodeport
  name: django-nodeport
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
  sessionAffinity: None
  type: NodePort
